### ISSUE TITLE
ResNeSt backbone got error when Infering

### ISSUE THREAD

**Issue by zehuichen123** [open-mmlab/mmdetection#4278] opened 2020-12-10 13:43 UTC
I am trying to use ResNeSt50 in my experiments. However, I got the following error when inferring model:
```python
File "/home/chenzehui.123/mmdetection/mmdet/models/backbones/resnest.py", line 241, in _inner_forward
    out = self.conv2(out)
  File "/data00/chenzehui.123/anaconda3/envs/mmdet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
  File "/home/chenzehui.123/mmdetection/mmdet/models/backbones/resnest.py", line 135, in forward
    result = self.forward(*input, **kwargs)
  File "/home/chenzehui.123/mmdetection/mmdet/models/backbones/resnest.py", line 135, in forward
    gap = self.norm1(gap)
    raise ValueError('Expected more than 1 value per channel when training, got input size {}'.format(size))
ValueError: Expected more than 1 value per channel when training, got input size [1, 32, 1, 1]
```

**Comment by v-qjqs** [comment] 2020-12-10 13:50
Duplicate of #4180

**Comment by zehuichen123** [comment] 2020-12-10 15:59
It seems that I am not in eval mode when inference? BN/GN does not support 1x1 input size when training.

**Closed** 2020-12-10 17:12 UTC
