### ISSUE TITLE
mmcv import error

### ISSUE THREAD

**Issue by yuyijie1995** [open-mmlab/mmdetection#1650] opened 2019-11-09 10:04 UTC
I have already installed the mmcv module .And I can import mmcv successful,like below.
```
>>> import mmcv
>>>
```
but when I use the python tools/test.py configs/faster_rcnn_r50_caffe_c4_1x.py checkpoints/faster_rcnn_r50_caffe_c4_1x-75ecfdfa.pth --show
the error happened ‘No module named 'mmcv' ’
I do not know how to fix it.

**Comment by ZwwWayne** [comment] 2019-11-10 04:27
It might because you run the script in a different environment, please check that first.

Btw, we will appreciate it if you could use the ` Error Template`.

**Comment by yuyijie1995** [comment] 2019-11-10 04:52
Thank you for your reply, I found that if I use tmux this error will happen and this command can run in a seperate window .

**Comment by ZwwWayne** [comment] 2019-11-10 05:39
> Thank you for your reply, I found that if I use tmux this error will happen and this command can run in a seperate window .

OK, this is because Tmux sometimes cannot import the environments successfully and you might need to check the environment by commands like `which python`.

I think the problem is solved so I will close this issue, feel free to reopen it if you have any further questions.

**Closed by ZwwWayne** 2019-11-10 05:39 UTC
