### ISSUE TITLE
the question of featmap_strides in roi_head

### ISSUE THREAD

**Issue by liuyanzhi1214** [open-mmlab/mmdetection#4478] opened 2021-01-19 08:45 UTC
rpn_head=dict(
        type='RPNHead',
        in_channels=256,
        feat_channels=256,
        anchor_generator=dict(
            type='AnchorGenerator',
            scales=[8],
            ratios=[0.5, 1.0, 2.0],
            **strides=[4, 8, 16, 32, 64]**),
        bbox_coder=dict(
            type='DeltaXYWHBBoxCoder',
            target_means=[0.0, 0.0, 0.0, 0.0],
            target_stds=[1.0, 1.0, 1.0, 1.0]),
        loss_cls=dict(
            type='FocalLoss',
            use_sigmoid=True,
            gamma=2,
            alpha=0.25,
            loss_weight=1.0),
        loss_bbox=dict(type='SmoothL1Loss', beta=1.0, loss_weight=1.0)),
    roi_head=dict(
        type='StandardRoIHead',
        bbox_roi_extractor=dict(
            type='SingleRoIExtractor',
            roi_layer=dict(type='RoIAlign', output_size=7, sampling_ratio=0),
            out_channels=256,
            **featmap_strides=[4, 8, 16, 32]**),
        bbox_head=dict(
            type='Shared4Conv1FCBBoxHead',
            in_channels=256,
            fc_out_channels=1024,
            roi_feat_size=7,
            num_classes=2,
            bbox_coder=dict(
                type='DeltaXYWHBBoxCoder',
                target_means=[0.0, 0.0, 0.0, 0.0], 
                target_stds=[0.1, 0.1, 0.2, 0.2]),
            reg_class_agnostic=False,
            loss_cls=dict(
                type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0),
            loss_bbox=dict(type='SmoothL1Loss', beta=1.0, loss_weight=1.0),
            conv_out_channels=256,
            norm_cfg=dict(type='BN', requires_grad=True))))
the FPN output 5 level(p2-p6),why there are only 4 level be uesd in roi_extractor?

**Comment by hhaAndroid** [comment] 2021-01-20 02:20
@liuyanzhi1214 hi, You can refer to the [FPN](https://arxiv.org/abs/1612.03144)

**Comment by ZwwWayne** [comment] 2021-01-24 15:03
The implementation follows the description and official code release of FPN.
The issue is closed as the question seems to be answered. Feel free to reopen it if you have any further questions.

**Closed by ZwwWayne** 2021-01-24 15:03 UTC
