### ISSUE TITLE
Using pre-trained HTC model for inference doesn't work

### ISSUE THREAD

**Issue by rohit-gupta** [open-mmlab/mmdetection#2187] opened 2020-03-02 02:17 UTC
When I try to run inference with the best HTC model, I get an error when trying to load the model

```
>>>from mmdet.apis import init_detector, inference_detector, show_result
>>>import mmcv
>>>config_file = "mmdetection/configs/htc/htc_dconv_c3-c5_mstrain_400_1400_x101_64x4d_fpn_20e.py"
>>>checkpoint_file = 'checkpoints/htc_dconv_c3-c5_mstrain_400_1400_x101_64x4d_fpn_20e_20190408-0e50669c.pth'
>>>model = init_detector(config_file, checkpoint_file, device='cuda:0')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rohitg/aicity2020/detection/mmdetection/mmdet/apis/inference.py", line 34, in init_detector
    model = build_detector(config.model, test_cfg=config.test_cfg)
  File "/home/rohitg/aicity2020/detection/mmdetection/mmdet/models/builder.py", line 43, in build_detector
    return build(cfg, DETECTORS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/home/rohitg/aicity2020/detection/mmdetection/mmdet/models/builder.py", line 15, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/home/rohitg/aicity2020/detection/mmdetection/mmdet/utils/registry.py", line 79, in build_from_cfg
    return obj_cls(**args)
  File "/home/rohitg/aicity2020/detection/mmdetection/mmdet/models/detectors/htc.py", line 24, in __init__
    super(HybridTaskCascade, self).__init__(num_stages, backbone, **kwargs)
  File "/home/rohitg/aicity2020/detection/mmdetection/mmdet/models/detectors/cascade_rcnn.py", line 36, in __init__
    self.backbone = builder.build_backbone(backbone)
  File "/home/rohitg/aicity2020/detection/mmdetection/mmdet/models/builder.py", line 19, in build_backbone
    return build(cfg, BACKBONES)
  File "/home/rohitg/aicity2020/detection/mmdetection/mmdet/models/builder.py", line 15, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/home/rohitg/aicity2020/detection/mmdetection/mmdet/utils/registry.py", line 79, in build_from_cfg
    return obj_cls(**args)
  File "/home/rohitg/aicity2020/detection/mmdetection/mmdet/models/backbones/resnext.py", line 190, in __init__
    super(ResNeXt, self).__init__(**kwargs)
  File "/home/rohitg/aicity2020/detection/mmdetection/mmdet/models/backbones/resnet.py", line 428, in __init__
    gen_attention_blocks=stage_with_gen_attention[i])
  File "/home/rohitg/aicity2020/detection/mmdetection/mmdet/models/backbones/resnet.py", line 285, in make_res_layer
    (0 in gen_attention_blocks) else None))
  File "/home/rohitg/aicity2020/detection/mmdetection/mmdet/models/backbones/resnext.py", line 66, in __init__
    bias=False)
  File "/home/rohitg/aicity2020/detection/mmdetection/mmdet/models/utils/conv_module.py", line 42, in build_conv_layer
    layer = conv_layer(*args, **kwargs, **cfg_)
TypeError: type object got multiple values for keyword argument 'groups'

```

Result of collect_env:
```shell
(pytorch1-3) rohitg@c3-4:~/aicity2020/detection/mmdetection$ python mmdet/utils/collect_env.py
sys.platform: linux
Python: 3.7.6 (default, Jan  8 2020, 19:59:22) [GCC 7.3.0]
CUDA available: True
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 9.2, V9.2.148
GPU 0,1: Quadro RTX 5000
GCC: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
PyTorch: 1.3.1
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.20.5 (Git Hash 0125f28c61c1f822fd48570b4c1066f96fcb9b2e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=True, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.4.2
OpenCV: 4.2.0
MMCV: 0.3.2
MMDetection: 1.1.0+9f6cddf
MMDetection Compiler: GCC 5.4
MMDetection CUDA Compiler: 9.2

```

**UPDATE:**

I have looked into this a bit, and it does seem like a bug, the conv_layer is being passed "groups" in both kwargs and cfg_ somehow. Which is weird given I am using the config file included in the repo.

kwargs -> ```{'kernel_size': 3, 'stride': 2, 'padding': 1, 'dilation': 1, 'groups': 1, 'bias': False}```
cfg_ -> ```{'groups': 64, 'deformable_groups': 1}```

**Comment by ZwwWayne** [comment] 2020-03-03 05:26
Hi @rohit-gupta ,
Thanks for your bug report, this is because the `groups` are also defined in the dcn config.
Deleting this [line](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/backbones/resnext.py#L65) could fix this bug.
If you fix the bug, would you like to create a PR to fix it in the codebase?

**Comment by rohit-gupta** [comment] 2020-03-04 23:45
@ZwwWayne Thanks for the pointer, I will take a look at this over the weekend and see if I can fix it.

**Comment by ZwwWayne** [comment] 2020-03-09 14:34
The issue is duplicated to issue https://github.com/open-mmlab/mmdetection/issues/2122 so it is closed. The bug will be fixed in the PR https://github.com/open-mmlab/mmdetection/pull/2221. Feel free to reopen it if you have any further questions.

**Closed by ZwwWayne** 2020-03-09 14:34 UTC

**Comment by rohit-gupta** [comment] 2020-03-10 20:47
Many thanks @ZwwWayne !

**Comment by mangdian** [comment] 2020-05-13 09:17
Hi, when I use the official pretrained HTC models to inference, the results just make no sense. The details is in [https://github.com/open-mmlab/mmdetection/issues/2697](url). Is there anything specificial with HRC inference? Hope you can help me, please

**Comment by ZwwWayne** [comment] 2020-05-14 09:03
Hi @mangdian , maybe you can lower down the score threshold?

**Comment by mangdian** [comment] 2020-05-14 09:07
@ZwwWayne I tried lowering the score threshold to 0.001, but there is not much difference

**Comment by mangdian** [comment] 2020-05-14 09:08
@ZwwWayne It seems that only small object are detected and segmented.

**Comment by ZwwWayne** [comment] 2020-05-14 09:20
You can test  the AP of this model to see whether the  AP matches the model zoo's results. And the codebase have already updated to v2.0, users are recommended to use the new codebase with new model zoo.

**Comment by mangdian** [comment] 2020-05-14 09:25
Yes I am using v2.0. Every other models works fine except HTC.

**Comment by ZwwWayne** [comment] 2020-05-14 09:28
> Yes I am using v2.0. Every other models works fine except HTC.

Try to test the AP first, and if the problem still exists, raise a new issue using the `Error Template`.
