### ISSUE TITLE
Train failed when executing e2e test case.

### ISSUE THREAD

**Issue by del-zhenwu** [open-mmlab/mmdetection#7223] opened 2022-02-23 02:55 UTC
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**

**Reproduction**

```
[2022-02-23T02:49:34.985Z] test_integration/test_train.py::TestTrain::test_train_config[/opt/mmdetection/configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py] FAILED [100%]

[2022-02-23T02:49:34.985Z] 

[2022-02-23T02:49:34.985Z] =================================== FAILURES ===================================

[2022-02-23T02:49:34.985Z] _ TestTrain.test_train_config[/opt/mmdetection/configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py] _

[2022-02-23T02:49:34.985Z] 

[2022-02-23T02:49:34.985Z] self = <test_integration.test_train.TestTrain object at 0x7fa2e7b652d0>

[2022-02-23T02:49:34.985Z] cmd_param = '/opt/mmdetection/configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py'

[2022-02-23T02:49:34.985Z] 

[2022-02-23T02:49:34.986Z]     @pytest.mark.usefixtures('prep')

[2022-02-23T02:49:34.986Z]     @pytest.mark.parametrize('cmd_param', param_config())

[2022-02-23T02:49:34.986Z]     def test_train_config(self, cmd_param):

[2022-02-23T02:49:34.986Z]         """

[2022-02-23T02:49:34.986Z]         Function: test train.py

[2022-02-23T02:49:34.986Z]     

[2022-02-23T02:49:34.986Z]         :param cmd_param: the command user use to call train.py

[2022-02-23T02:49:34.986Z]         :return:

[2022-02-23T02:49:34.986Z]         """

[2022-02-23T02:49:34.986Z]         file_path = os.path.join(pytest.CODEB_PATH, 'tools/train.py')

[2022-02-23T02:49:34.986Z]         cmd = "python " + file_path + ' ' + cmd_param \

[2022-02-23T02:49:34.986Z]               + ' ' + '--cfg-options data.workers_per_gpu=0 data.samples_per_gpu=1 train_pipeline.2.img_scale=(1333,128) runner.max_epochs=1' # the cmd to be executed

[2022-02-23T02:49:34.986Z]         res = subprocess.run(cmd.split(' '))

[2022-02-23T02:49:34.986Z] >       assert res.returncode == 0, \

[2022-02-23T02:49:34.986Z]             'Failed to run train.py with parameter [config] set'

[2022-02-23T02:49:34.986Z] E       AssertionError: Failed to run train.py with parameter [config] set

[2022-02-23T02:49:34.986Z] E       assert 1 == 0

[2022-02-23T02:49:34.986Z] E         +1

[2022-02-23T02:49:34.986Z] E         -0

[2022-02-23T02:49:34.986Z] 

[2022-02-23T02:49:34.986Z] test_integration/test_train.py:48: AssertionError

...

[2022-02-23T02:49:34.992Z] 2022-02-23 02:48:59,425 - mmcv - WARNING - The model and loaded state dict do not match exactly

[2022-02-23T02:49:34.992Z] 

[2022-02-23T02:49:34.992Z] unexpected key in source state_dict: fc.weight, fc.bias

[2022-02-23T02:49:34.992Z] 

[2022-02-23T02:49:34.992Z] 2022-02-23 02:48:59,646 - mmdet - INFO - initialize FPN with init_cfg {'type': 'Xavier', 'layer': 'Conv2d', 'distribution': 'uniform'}

[2022-02-23T02:49:34.992Z] 2022-02-23 02:48:59,829 - mmdet - INFO - initialize RPNHead with init_cfg {'type': 'Normal', 'layer': 'Conv2d', 'std': 0.01}

[2022-02-23T02:49:34.992Z] 2022-02-23 02:48:59,926 - mmdet - INFO - initialize Shared2FCBBoxHead with init_cfg [{'type': 'Normal', 'std': 0.01, 'override': {'name': 'fc_cls'}}, {'type': 'Normal', 'std': 0.001, 'override': {'name': 'fc_reg'}}, {'type': 'Xavier', 'distribution': 'uniform', 'override': [{'name': 'shared_fcs'}, {'name': 'cls_fcs'}, {'name': 'reg_fcs'}]}]

[2022-02-23T02:49:34.992Z] 2022-02-23 02:49:05,090 - mmdet - INFO - Start running, host: root@mmdetection-build-test-80-5046ad-s5dbc, work_dir: /opt/mmdetection/openmmlab-ci/e2e/mmdetection/work_dirs/faster_rcnn_r50_fpn_1x_coco

[2022-02-23T02:49:34.992Z] 2022-02-23 02:49:05,091 - mmdet - INFO - Hooks will be executed in the following order:

[2022-02-23T02:49:34.992Z] before_run:

[2022-02-23T02:49:34.992Z] (VERY_HIGH   ) StepLrUpdaterHook                  

[2022-02-23T02:49:34.992Z] (NORMAL      ) CheckpointHook                     

[2022-02-23T02:49:34.992Z] (LOW         ) EvalHook                           

[2022-02-23T02:49:34.992Z] (VERY_LOW    ) TextLoggerHook                     

[2022-02-23T02:49:34.992Z]  -------------------- 

[2022-02-23T02:49:34.992Z] before_train_epoch:

[2022-02-23T02:49:34.992Z] (VERY_HIGH   ) StepLrUpdaterHook                  

[2022-02-23T02:49:34.992Z] (NORMAL      ) NumClassCheckHook                  

[2022-02-23T02:49:34.992Z] (LOW         ) IterTimerHook                      

[2022-02-23T02:49:34.992Z] (LOW         ) EvalHook                           

[2022-02-23T02:49:34.992Z] (VERY_LOW    ) TextLoggerHook                     

[2022-02-23T02:49:34.992Z]  -------------------- 

[2022-02-23T02:49:34.992Z] before_train_iter:

[2022-02-23T02:49:34.992Z] (VERY_HIGH   ) StepLrUpdaterHook                  

[2022-02-23T02:49:34.992Z] (LOW         ) IterTimerHook                      

[2022-02-23T02:49:34.992Z] (LOW         ) EvalHook                           

[2022-02-23T02:49:34.992Z]  -------------------- 

[2022-02-23T02:49:34.992Z] after_train_iter:

[2022-02-23T02:49:34.992Z] (ABOVE_NORMAL) OptimizerHook                      

[2022-02-23T02:49:34.992Z] (NORMAL      ) CheckpointHook                     

[2022-02-23T02:49:34.992Z] (LOW         ) IterTimerHook                      

[2022-02-23T02:49:34.993Z] (LOW         ) EvalHook                           

[2022-02-23T02:49:34.993Z] (VERY_LOW    ) TextLoggerHook                     

[2022-02-23T02:49:34.993Z]  -------------------- 

[2022-02-23T02:49:34.993Z] after_train_epoch:

[2022-02-23T02:49:34.993Z] (NORMAL      ) CheckpointHook                     

[2022-02-23T02:49:34.993Z] (LOW         ) EvalHook                           

[2022-02-23T02:49:34.993Z] (VERY_LOW    ) TextLoggerHook                     

[2022-02-23T02:49:34.993Z]  -------------------- 

[2022-02-23T02:49:34.993Z] before_val_epoch:

[2022-02-23T02:49:34.993Z] (NORMAL      ) NumClassCheckHook                  

[2022-02-23T02:49:34.993Z] (LOW         ) IterTimerHook                      

[2022-02-23T02:49:34.993Z] (VERY_LOW    ) TextLoggerHook                     

[2022-02-23T02:49:34.993Z]  -------------------- 

[2022-02-23T02:49:34.993Z] before_val_iter:

[2022-02-23T02:49:34.993Z] (LOW         ) IterTimerHook                      

[2022-02-23T02:49:34.993Z]  -------------------- 

[2022-02-23T02:49:34.993Z] after_val_iter:

[2022-02-23T02:49:34.993Z] (LOW         ) IterTimerHook                      

[2022-02-23T02:49:34.993Z]  -------------------- 

[2022-02-23T02:49:34.993Z] after_val_epoch:

[2022-02-23T02:49:34.993Z] (VERY_LOW    ) TextLoggerHook                     

[2022-02-23T02:49:34.993Z]  -------------------- 

[2022-02-23T02:49:34.993Z] after_run:

[2022-02-23T02:49:34.993Z] (VERY_LOW    ) TextLoggerHook                     

[2022-02-23T02:49:34.993Z]  -------------------- 

[2022-02-23T02:49:34.993Z] 2022-02-23 02:49:05,092 - mmdet - INFO - workflow: [('train', 1)], max: 1 epochs

[2022-02-23T02:49:34.993Z] 2022-02-23 02:49:05,092 - mmdet - INFO - Checkpoints will be saved to /opt/mmdetection/openmmlab-ci/e2e/mmdetection/work_dirs/faster_rcnn_r50_fpn_1x_coco by HardDiskBackend.

[2022-02-23T02:49:34.993Z] Traceback (most recent call last):

[2022-02-23T02:49:34.993Z]   File "/opt/mmdetection/tools/train.py", line 209, in <module>

[2022-02-23T02:49:34.993Z]     main()

[2022-02-23T02:49:34.993Z]   File "/opt/mmdetection/tools/train.py", line 205, in main

[2022-02-23T02:49:34.993Z]     meta=meta)

[2022-02-23T02:49:34.993Z]   File "/opt/conda/lib/python3.7/site-packages/mmdet/apis/train.py", line 208, in train_detector

[2022-02-23T02:49:34.993Z]     runner.run(data_loaders, cfg.workflow)

[2022-02-23T02:49:34.993Z]   File "/opt/mmcv/mmcv/runner/epoch_based_runner.py", line 127, in run

[2022-02-23T02:49:34.993Z]     epoch_runner(data_loaders[i], **kwargs)

[2022-02-23T02:49:34.993Z]   File "/opt/mmcv/mmcv/runner/epoch_based_runner.py", line 47, in train

[2022-02-23T02:49:34.993Z]     for i, data_batch in enumerate(self.data_loader):

[2022-02-23T02:49:34.993Z]   File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 363, in __next__

[2022-02-23T02:49:34.993Z]     data = self._next_data()

[2022-02-23T02:49:34.993Z]   File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 403, in _next_data

[2022-02-23T02:49:34.993Z]     data = self._dataset_fetcher.fetch(index)  # may raise StopIteration

[2022-02-23T02:49:34.993Z]   File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch

[2022-02-23T02:49:34.993Z]     data = [self.dataset[idx] for idx in possibly_batched_index]

[2022-02-23T02:49:34.993Z]   File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>

[2022-02-23T02:49:34.993Z]     data = [self.dataset[idx] for idx in possibly_batched_index]

[2022-02-23T02:49:34.993Z]   File "/opt/conda/lib/python3.7/site-packages/mmdet/datasets/custom.py", line 218, in __getitem__

[2022-02-23T02:49:34.993Z]     data = self.prepare_train_img(idx)

[2022-02-23T02:49:34.993Z]   File "/opt/conda/lib/python3.7/site-packages/mmdet/datasets/custom.py", line 241, in prepare_train_img

[2022-02-23T02:49:34.993Z]     return self.pipeline(results)

[2022-02-23T02:49:34.993Z]   File "/opt/conda/lib/python3.7/site-packages/mmdet/datasets/pipelines/compose.py", line 41, in __call__

[2022-02-23T02:49:34.993Z]     data = t(data)

[2022-02-23T02:49:34.993Z]   File "/opt/conda/lib/python3.7/site-packages/mmdet/datasets/pipelines/loading.py", line 73, in __call__

[2022-02-23T02:49:34.993Z]     results['img_shape'] = img.shape

[2022-02-23T02:49:34.993Z] AttributeError: 'NoneType' object has no attribute 'shape'


```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
3. What dataset did you use?

**Environment**
branch: `dev`

```

[2022-02-23T02:49:34.986Z] sys.platform: linux

[2022-02-23T02:49:34.986Z] Python: 3.7.7 (default, May  7 2020, 21:25:33) [GCC 7.3.0]

[2022-02-23T02:49:34.986Z] CUDA available: True

[2022-02-23T02:49:34.986Z] GPU 0: Tesla T4

[2022-02-23T02:49:34.986Z] CUDA_HOME: /usr/local/cuda

[2022-02-23T02:49:34.986Z] NVCC: Cuda compilation tools, release 10.1, V10.1.243

[2022-02-23T02:49:34.986Z] GCC: gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0

[2022-02-23T02:49:34.986Z] PyTorch: 1.6.0

[2022-02-23T02:49:34.986Z] PyTorch compiling details: PyTorch built with:

[2022-02-23T02:49:34.986Z]   - GCC 7.3

[2022-02-23T02:49:34.986Z]   - C++ Version: 201402

[2022-02-23T02:49:34.986Z]   - Intel(R) Math Kernel Library Version 2020.0.1 Product Build 20200208 for Intel(R) 64 architecture applications

[2022-02-23T02:49:34.986Z]   - Intel(R) MKL-DNN v1.5.0 (Git Hash e2ac1fac44c5078ca927cb9b90e1b3066a0b2ed0)

[2022-02-23T02:49:34.986Z]   - OpenMP 201511 (a.k.a. OpenMP 4.5)

[2022-02-23T02:49:34.986Z]   - NNPACK is enabled

[2022-02-23T02:49:34.986Z]   - CPU capability usage: AVX

[2022-02-23T02:49:34.986Z]   - CUDA Runtime 10.1

[2022-02-23T02:49:34.986Z]   - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37

[2022-02-23T02:49:34.986Z]   - CuDNN 7.6.3

[2022-02-23T02:49:34.986Z]   - Magma 2.5.2

[2022-02-23T02:49:34.986Z]   - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

[2022-02-23T02:49:34.986Z] 

[2022-02-23T02:49:34.986Z] TorchVision: 0.7.0

[2022-02-23T02:49:34.986Z] OpenCV: 4.5.5

[2022-02-23T02:49:34.986Z] MMCV: 1.4.4

[2022-02-23T02:49:34.986Z] MMCV Compiler: GCC 7.4

[2022-02-23T02:49:34.986Z] MMCV CUDA Compiler: 10.1

[2022-02-23T02:49:34.986Z] MMDetection: 2.21.0+cdbdf49

```

**Error traceback**
If applicable, paste the error trackback here.

```none
A placeholder for trackback.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by ZwwWayne** [comment] 2022-02-23 11:46
It seems that the images are not successfully loaded, thus the img is None. Which dataset are you using?

**Comment by ZwwWayne** [comment] 2022-03-03 13:18
This issue is closed as it is caused by the failure of downloading data.

**Closed by ZwwWayne** 2022-03-03 13:18 UTC
