### ISSUE TITLE
Test Albu with mask_rcnn_r50_fpn_albu_1x_coco.py failure

### ISSUE THREAD

**Issue by minan19605** [open-mmlab/mmdetection#4035] opened 2020-10-30 18:33 UTC
**Describe the bug**
I try to use Albu with my coco format dataset.  I use the sample configuration in the "mmdetection\configs\albu_example". But it can't work:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
_**Seems when Albu code check the data of mask, report this error**_

**Environment**

2020-10-30 13:26:44,905 - mmdet - INFO - Environment info:
------------------------------------------------------------
sys.platform: linux
Python: 3.7.7 (default, May  7 2020, 21:25:33) [GCC 7.3.0]
CUDA available: True
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.1, V10.1.243
GPU 0: GeForce RTX 2070
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.5.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.1 Product Build 20200208 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_INTERNAL_THREADPOOL_IMPL -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.6.0a0+82fd1c8
OpenCV: 4.4.0
MMCV: 1.0.5
MMDetection: 2.3.0+68d860d
MMDetection Compiler: GCC 7.5
MMDetection CUDA Compiler: 10.1

**Error traceback**
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/minan/anaconda3/envs/mmdet/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/minan/anaconda3/envs/mmdet/lib/python3.7/site-packages/prefetch_generator/__init__.py", line 80, in run
    for item in self.generator:
  File "/home/minan/anaconda3/envs/mmdet/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/minan/anaconda3/envs/mmdet/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/home/minan/anaconda3/envs/mmdet/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/home/minan/anaconda3/envs/mmdet/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/minan/anaconda3/envs/mmdet/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/minan/anaconda3/envs/mmdet/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/minan/anaconda3/envs/mmdet/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/minan/mmdet/mmdetection/mmdet/datasets/custom.py", line 187, in __getitem__
    data = self.prepare_train_img(idx)
  File "/home/minan/mmdet/mmdetection/mmdet/datasets/custom.py", line 210, in prepare_train_img
    return self.pipeline(results)
  File "/home/minan/mmdet/mmdetection/mmdet/datasets/pipelines/compose.py", line 40, in __call__
    data = t(data)
  File "/home/minan/mmdet/mmdetection/mmdet/datasets/pipelines/transforms.py", line 1152, in __call__
    results = self.aug(**results)
  File "/home/minan/anaconda3/envs/mmdet/lib/python3.7/site-packages/albumentations/core/composition.py", line 166, in __call__
    self._check_args(**data)
  File "/home/minan/anaconda3/envs/mmdet/lib/python3.7/site-packages/albumentations/core/composition.py", line 223, in _check_args
    if data:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by akshit61** [comment] 2020-11-05 06:30
I am facing the same error

**Comment by Augustusmyc** [comment] 2020-11-05 09:17
I am facing the same error

**Comment by minan19605** [comment] 2020-11-05 15:00
I comment on line 166:

anaconda3/envs/mmdet/lib/python3.7/site-packages/albumentations/core/composition.py", line 166,
**\#self._check_args(**data)**
Now training and test are working well.

**Comment by v-qjqs** [comment] 2020-11-23 09:38
Duplicate of #4079.

**Closed by v-qjqs** 2020-11-23 09:38 UTC
