### ISSUE TITLE
Batch inference for custom dataset

### ISSUE THREAD

**Issue by moonh1** [open-mmlab/mmdetection#1552] opened 2019-10-16 08:00 UTC
Hello, I have been trying to test custom data.
The model I am using is cascade-rcnn, and I succeeded test with inference_demo.ipynb file.

Now, I am trying to implement batch inference, and having hard time doing this.
What I have tried are,
    1) tried by changing mmdetection/mmdet/apis/inference.py, specifically by changing only 
        data['img'][0] from 'data' 
    2) referred tools/test.py to modify the code not to use coco datatype, but failed since it uses 
        pytorch dataloader format.

Can anyone suggest a way to implement batch inference?
Thank you so much.

**Comment by ash11sh** [comment] 2019-11-27 06:26
Duplicate of #1659

**Closed** 2019-12-02 12:19 UTC
