### ISSUE TITLE
[Errno 36] File name too long

### ISSUE THREAD

**Issue by finnickniu** [open-mmlab/mmdetection#3631] opened 2020-08-27 04:51 UTC
When I run the following code
```
python demo/webcam_demo.py configs/cascade_rcnn/cascade_rcnn_r50_fpn_20e_coco.py models/cascade_rcnn_r50_fpn_20e_coco_bbox_mAP-0.41_20200504_175131-e9872a90.pth

```

There is an error:

OSError: [Errno 36] File name too long: '[[[120 132 105]\n  [120 132 105]\n  [119 131 104]\n  ...\n  [ 19  19  17]\n  [ 19  19  17]\n  [ 19  19  17]]\n\n [[120 132 105]\n  [120 132 105]\n  [119 131 104]\n  ...\n  [ 19  19  17]\n  [ 19  20  17]\n  [ 19  20  17]]\n\n [[119 132 105]\n  [119 132 105]\n  [118 131 104]\n  ...\n  [ 20  21  17]\n  [ 20  21  18]\n  [ 20  21  18]]\n\n ...\n\n [[179 180 177]\n  [179 180 177]\n  [179 180 177]\n  ...\n  [182 186 183]\n  [182 187 183]\n  [182 187 183]]\n\n [[179 180 178]\n  [179 180 178]\n  [179 180 178]\n  ...\n  [183 186 183]\n  [183 187 184]\n  [183 187 184]]\n\n [[179 180 178]\n  [179 180 178]\n  [179 180 178]\n  ...\n  [183 186 184]\n  [184 187 185]\n  [184 187 185]]]'

**Comment by v-qjqs** [comment] 2020-08-27 05:19
Hi, it is a bug and will be fixed soon.
Duplicate of #3623

**Closed** 2020-08-28 11:14 UTC
