### ISSUE TITLE
I'm Microsoft Research Institute. When I add a custom backbone, I will be prompted with an error of no registration

### ISSUE THREAD

**Issue by xianglei3** [open-mmlab/mmdetection#6596] opened 2021-11-26 07:48 UTC
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**

**Reproduction**

1. What command or script did you run?

```none
A placeholder for the command.
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
3. What dataset did you use?

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.
Traceback (most recent call last):
  File "./tools/train.py", line 189, in <module>
    main()
  File "./tools/train.py", line 162, in main
    test_cfg=cfg.get('test_cfg'))
  File "/home/kny/code/cell/mmdet/models/builder.py", line 58, in build_detector
    cfg, default_args=dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/home/kny/anaconda3/envs/mmd/lib/python3.7/site-packages/mmcv/utils/registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/kny/anaconda3/envs/mmd/lib/python3.7/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/kny/anaconda3/envs/mmd/lib/python3.7/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
KeyError: "CascadeRCNN: 'EfficientNet is not in the models registry'"
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 51212) of binary: /home/kny/anaconda3/envs/mmd/bin/python
Traceback (most recent call last):
  File "/home/kny/anaconda3/envs/mmd/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/kny/anaconda3/envs/mmd/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/kny/anaconda3/envs/mmd/lib/python3.7/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/kny/anaconda3/envs/mmd/lib/python3.7/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/kny/anaconda3/envs/mmd/lib/python3.7/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/kny/anaconda3/envs/mmd/lib/python3.7/site-packages/torch/distributed/run.py", line 713, in run
    )(*cmd_args)
  File "/home/kny/anaconda3/envs/mmd/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/kny/anaconda3/envs/mmd/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 261, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 

```none
A placeholder for trackback.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by BIGWangYuDong** [comment] 2021-11-26 08:47
KeyError: "CascadeRCNN: 'EfficientNet is not in the models registry'"

you should add EfficientNet in init.py and more details you can refer to https://mmdetection.readthedocs.io/en/v2.18.1/tutorials/customize_models.html

**Comment by xianglei3** [comment] 2021-11-29 08:43
> KeyError: "CascadeRCNN: 'EfficientNet is not in the models registry'"
> 
> you should add EfficientNet in init.py and more details you can refer to https://mmdetection.readthedocs.io/en/v2.18.1/tutorials/customize_models.html

I do, an err  occur 
  File "/home/kny/code/cell/mmdet/models/necks/fpn.py", line 153, in forward
    assert len(inputs) == len(self.in_channels)

**Comment by k-jeon** [comment] 2022-01-28 01:08
Hello, I got the same error:

```
sys.platform: linux
Python: 3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 06:08:53) [GCC 9.4.0]
CUDA available: True
GPU 0: Tesla T4
CUDA_HOME: /usr/local/cuda
NVCC: Build cuda_11.0_bu.TC445_37.28845127_0
GCC: gcc (Debian 8.3.0-6) 8.3.0
PyTorch: 1.10.1+cu111
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX512
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.11.2+cu111
OpenCV: 4.5.5
MMCV: 1.4.4
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 11.1
MMDetection: 2.20.0+ff9bc39
```

I followed [Tutorial 4: Customize Models](https://mmdetection.readthedocs.io/en/latest/tutorials/customize_models.html) exactly except for that my `mobilenet.py` is a duplicate of `mobilenet_v2.py`. Also I replaced `MobileNetV2` with `MobileNet` in the file. I also added the following line in `__init__.py`.
```
from .mobilenet import MobileNet
```

To test, I replaced `MobileNetV2` with `MobileNet` in `configs/yolo/yolov3_mobilenetv2_mstrain-416_300e_coco.py`. 

 Since the new backbone is same as `MobileNetV2`, I thought I can use the same pretrained model. So I ran the following snippet:

```python
from mmdet.apis import init_detector, inference_detector

config_file = 'configs/yolo/yolov3_mobilenetv2_mstrain-416_300e_coco.py'
# download the checkpoint from model zoo and put it in `checkpoints/`
# url: https://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_1x_coco/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth
#checkpoint_file = 'ckpts/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth'
checkpoint_file = 'ckpts/yolov3_mobilenetv2_mstrain-416_300e_coco_20210718_010823-f68a07b3.pth'
device = 'cuda:0'
# init a detector
model = init_detector(config_file, checkpoint_file, device=device)
# inference the demo image
inference_detector(model, 'demo/demo.jpg')
```

But the following error occurs:

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/opt/conda/lib/python3.7/site-packages/mmcv/utils/registry.py in build_from_cfg(cfg, registry, default_args)
     51     try:
---> 52         return obj_cls(**args)
     53     except Exception as e:

~/mmdetection/mmdet/models/detectors/yolo.py in __init__(self, backbone, neck, bbox_head, train_cfg, test_cfg, pretrained, init_cfg)
     20         super(YOLOV3, self).__init__(backbone, neck, bbox_head, train_cfg,
---> 21                                      test_cfg, pretrained, init_cfg)
     22 

~/mmdetection/mmdet/models/detectors/single_stage.py in __init__(self, backbone, neck, bbox_head, train_cfg, test_cfg, pretrained, init_cfg)
     31             backbone.pretrained = pretrained
---> 32         self.backbone = build_backbone(backbone)
     33         if neck is not None:

~/mmdetection/mmdet/models/builder.py in build_backbone(cfg)
     19     """Build backbone."""
---> 20     return BACKBONES.build(cfg)
     21 

/opt/conda/lib/python3.7/site-packages/mmcv/utils/registry.py in build(self, *args, **kwargs)
    211     def build(self, *args, **kwargs):
--> 212         return self.build_func(*args, **kwargs, registry=self)
    213 

/opt/conda/lib/python3.7/site-packages/mmcv/cnn/builder.py in build_model_from_cfg(cfg, registry, default_args)
     26     else:
---> 27         return build_from_cfg(cfg, registry, default_args)
     28 

/opt/conda/lib/python3.7/site-packages/mmcv/utils/registry.py in build_from_cfg(cfg, registry, default_args)
     44             raise KeyError(
---> 45                 f'{obj_type} is not in the {registry.name} registry')
     46     elif inspect.isclass(obj_type):

KeyError: 'MobileNet is not in the models registry'

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
/tmp/ipykernel_2770/1667732121.py in <module>
      8 device = 'cuda:0'
      9 # init a detector
---> 10 model = init_detector(config_file, checkpoint_file, device=device)
     11 # inference the demo image
     12 inference_detector(model, 'demo/demo.jpg')

~/mmdetection/mmdet/apis/inference.py in init_detector(config, checkpoint, device, cfg_options)
     38     config.model.pretrained = None
     39     config.model.train_cfg = None
---> 40     model = build_detector(config.model, test_cfg=config.get('test_cfg'))
     41     if checkpoint is not None:
     42         checkpoint = load_checkpoint(model, checkpoint, map_location='cpu')

~/mmdetection/mmdet/models/builder.py in build_detector(cfg, train_cfg, test_cfg)
     57         'test_cfg specified in both outer field and model field '
     58     return DETECTORS.build(
---> 59         cfg, default_args=dict(train_cfg=train_cfg, test_cfg=test_cfg))

/opt/conda/lib/python3.7/site-packages/mmcv/utils/registry.py in build(self, *args, **kwargs)
    210 
    211     def build(self, *args, **kwargs):
--> 212         return self.build_func(*args, **kwargs, registry=self)
    213 
    214     def _add_children(self, registry):

/opt/conda/lib/python3.7/site-packages/mmcv/cnn/builder.py in build_model_from_cfg(cfg, registry, default_args)
     25         return Sequential(*modules)
     26     else:
---> 27         return build_from_cfg(cfg, registry, default_args)
     28 
     29 

/opt/conda/lib/python3.7/site-packages/mmcv/utils/registry.py in build_from_cfg(cfg, registry, default_args)
     53     except Exception as e:
     54         # Normal TypeError does not print class name.
---> 55         raise type(e)(f'{obj_cls.__name__}: {e}')
     56 
     57 

KeyError: "YOLOV3: 'MobileNet is not in the models registry'"
```

**Comment by k-jeon** [comment] 2022-01-28 01:24
Restarting my Jupyter Notebook kernel solved the issue. :-)

@xianglei3, I guess your issue is now with your code?

**Comment by BIGWangYuDong** [comment] 2022-10-24 03:42
Feel free to create a new issue if you still meet problems

**Closed by BIGWangYuDong** 2022-10-24 03:42 UTC
